# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    style:
        label: indikator.popup::lang.form.style
        conditions: style in (:filtered)
        options:
            1: indikator.popup::lang.form.style_popup
            2: indikator.popup::lang.form.style_slide

    status_active:
        label: indikator.popup::lang.form.status_active
        type: checkbox
        conditions: status = 1

    status_inactive:
        label: indikator.popup::lang.form.status_inactive
        type: checkbox
        conditions: status = 2

    created_date:
        label: indikator.popup::lang.list.created_at
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'

    updated_date:
        label: indikator.popup::lang.list.updated_at
        type: daterange
        conditions: updated_at >= ':after' AND updated_at <= ':before'
