# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    status_active:
        label: indikator.popup::lang.form.status_active
        type: checkbox
        conditions: status = 1

    status_inactive:
        label: indikator.popup::lang.form.status_inactive
        type: checkbox
        conditions: status = 2

    view:
        label: indikator.popup::lang.report.view
        type: numberrange
        conditions: view >= ':min' and view <= ':max'

    action:
        label: indikator.popup::lang.report.action
        type: numberrange
        conditions: action >= ':min' and action <= ':max'

    created_date:
        label: indikator.popup::lang.list.created_at
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'

    updated_date:
        label: indikator.popup::lang.list.updated_at
        type: daterange
        conditions: updated_at >= ':after' AND updated_at <= ':before'
