# ===================================
#  List Behavior Config
# ===================================

title: indikator.popup::lang.menu.campaigns
list: ~/plugins/indikator/popup/models/campaigns/columns.yaml

modelClass: Indikator\Popup\Models\Campaigns
recordUrl: indikator/popup/campaigns/update/:id
noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 15
showCheckboxes: true
showSetup: true

defaultSort:
    column: name
    direction: asc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

filter: config_filter.yaml
